# coding: utf-8

"""
    Superna Eyeglass REST API

    A collection of utilities for programmatic interaction with Superna Eyeglass  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@superna.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class JobFailoverTarget(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'policies': 'list[Policy]',
        'zone': 'Zone'
    }

    attribute_map = {
        'policies': 'policies',
        'zone': 'zone'
    }

    def __init__(self, policies=None, zone=None, _configuration=None):  # noqa: E501
        """JobFailoverTarget - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._policies = None
        self._zone = None
        self.discriminator = None

        if policies is not None:
            self.policies = policies
        if zone is not None:
            self.zone = zone

    @property
    def policies(self):
        """Gets the policies of this JobFailoverTarget.  # noqa: E501

        The policies being failed over  # noqa: E501

        :return: The policies of this JobFailoverTarget.  # noqa: E501
        :rtype: list[Policy]
        """
        return self._policies

    @policies.setter
    def policies(self, policies):
        """Sets the policies of this JobFailoverTarget.

        The policies being failed over  # noqa: E501

        :param policies: The policies of this JobFailoverTarget.  # noqa: E501
        :type: list[Policy]
        """

        self._policies = policies

    @property
    def zone(self):
        """Gets the zone of this JobFailoverTarget.  # noqa: E501


        :return: The zone of this JobFailoverTarget.  # noqa: E501
        :rtype: Zone
        """
        return self._zone

    @zone.setter
    def zone(self, zone):
        """Sets the zone of this JobFailoverTarget.


        :param zone: The zone of this JobFailoverTarget.  # noqa: E501
        :type: Zone
        """

        self._zone = zone

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobFailoverTarget, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobFailoverTarget):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, JobFailoverTarget):
            return True

        return self.to_dict() != other.to_dict()
