# coding: utf-8

"""
    Superna Eyeglass REST API

    A collection of utilities for programmatic interaction with Superna Eyeglass  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@superna.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class VaultEventsDataConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'guid': 'str',
        'ip': 'str',
        'name': 'str',
        'version': 'str'
    }

    attribute_map = {
        'guid': 'guid',
        'ip': 'ip',
        'name': 'name',
        'version': 'version'
    }

    def __init__(self, guid=None, ip=None, name=None, version=None, _configuration=None):  # noqa: E501
        """VaultEventsDataConfig - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._guid = None
        self._ip = None
        self._name = None
        self._version = None
        self.discriminator = None

        if guid is not None:
            self.guid = guid
        if ip is not None:
            self.ip = ip
        if name is not None:
            self.name = name
        if version is not None:
            self.version = version

    @property
    def guid(self):
        """Gets the guid of this VaultEventsDataConfig.  # noqa: E501

        guid  # noqa: E501

        :return: The guid of this VaultEventsDataConfig.  # noqa: E501
        :rtype: str
        """
        return self._guid

    @guid.setter
    def guid(self, guid):
        """Sets the guid of this VaultEventsDataConfig.

        guid  # noqa: E501

        :param guid: The guid of this VaultEventsDataConfig.  # noqa: E501
        :type: str
        """

        self._guid = guid

    @property
    def ip(self):
        """Gets the ip of this VaultEventsDataConfig.  # noqa: E501

        Ip  # noqa: E501

        :return: The ip of this VaultEventsDataConfig.  # noqa: E501
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this VaultEventsDataConfig.

        Ip  # noqa: E501

        :param ip: The ip of this VaultEventsDataConfig.  # noqa: E501
        :type: str
        """

        self._ip = ip

    @property
    def name(self):
        """Gets the name of this VaultEventsDataConfig.  # noqa: E501

        name  # noqa: E501

        :return: The name of this VaultEventsDataConfig.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this VaultEventsDataConfig.

        name  # noqa: E501

        :param name: The name of this VaultEventsDataConfig.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def version(self):
        """Gets the version of this VaultEventsDataConfig.  # noqa: E501

        version  # noqa: E501

        :return: The version of this VaultEventsDataConfig.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this VaultEventsDataConfig.

        version  # noqa: E501

        :param version: The version of this VaultEventsDataConfig.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VaultEventsDataConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VaultEventsDataConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VaultEventsDataConfig):
            return True

        return self.to_dict() != other.to_dict()
