# coding: utf-8

"""
    Superna Eyeglass REST API

    A collection of utilities for programmatic interaction with Superna Eyeglass  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@superna.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Whitelist(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'changed': 'int',
        'items': 'list[str]',
        'type': 'str'
    }

    attribute_map = {
        'changed': 'changed',
        'items': 'items',
        'type': 'type'
    }

    def __init__(self, changed=None, items=None, type=None, _configuration=None):  # noqa: E501
        """Whitelist - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._changed = None
        self._items = None
        self._type = None
        self.discriminator = None

        if changed is not None:
            self.changed = changed
        if items is not None:
            self.items = items
        if type is not None:
            self.type = type

    @property
    def changed(self):
        """Gets the changed of this Whitelist.  # noqa: E501

        The time of last edit of this whitelist element  # noqa: E501

        :return: The changed of this Whitelist.  # noqa: E501
        :rtype: int
        """
        return self._changed

    @changed.setter
    def changed(self, changed):
        """Sets the changed of this Whitelist.

        The time of last edit of this whitelist element  # noqa: E501

        :param changed: The changed of this Whitelist.  # noqa: E501
        :type: int
        """

        self._changed = changed

    @property
    def items(self):
        """Gets the items of this Whitelist.  # noqa: E501

        the item list to be ignored in ransomware events detection  # noqa: E501

        :return: The items of this Whitelist.  # noqa: E501
        :rtype: list[str]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this Whitelist.

        the item list to be ignored in ransomware events detection  # noqa: E501

        :param items: The items of this Whitelist.  # noqa: E501
        :type: list[str]
        """

        self._items = items

    @property
    def type(self):
        """Gets the type of this Whitelist.  # noqa: E501

        path, user, source..  # noqa: E501

        :return: The type of this Whitelist.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Whitelist.

        path, user, source..  # noqa: E501

        :param type: The type of this Whitelist.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Whitelist, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Whitelist):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Whitelist):
            return True

        return self.to_dict() != other.to_dict()
