# coding: utf-8

"""
    Superna Eyeglass REST API

    A collection of utilities for programmatic interaction with Superna Eyeglass  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@superna.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class WritableSnapshotsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'job_id': 'str',
        'message': 'str',
        'snapshots': 'list[WritableSnapshotModel]',
        'success': 'str'
    }

    attribute_map = {
        'job_id': 'jobId',
        'message': 'message',
        'snapshots': 'snapshots',
        'success': 'success'
    }

    def __init__(self, job_id=None, message=None, snapshots=None, success=None, _configuration=None):  # noqa: E501
        """WritableSnapshotsResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._job_id = None
        self._message = None
        self._snapshots = None
        self._success = None
        self.discriminator = None

        if job_id is not None:
            self.job_id = job_id
        if message is not None:
            self.message = message
        if snapshots is not None:
            self.snapshots = snapshots
        if success is not None:
            self.success = success

    @property
    def job_id(self):
        """Gets the job_id of this WritableSnapshotsResponse.  # noqa: E501

        Job id of creating or deleting jobs of writable snapshots  # noqa: E501

        :return: The job_id of this WritableSnapshotsResponse.  # noqa: E501
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this WritableSnapshotsResponse.

        Job id of creating or deleting jobs of writable snapshots  # noqa: E501

        :param job_id: The job_id of this WritableSnapshotsResponse.  # noqa: E501
        :type: str
        """

        self._job_id = job_id

    @property
    def message(self):
        """Gets the message of this WritableSnapshotsResponse.  # noqa: E501

        Error Message  # noqa: E501

        :return: The message of this WritableSnapshotsResponse.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this WritableSnapshotsResponse.

        Error Message  # noqa: E501

        :param message: The message of this WritableSnapshotsResponse.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def snapshots(self):
        """Gets the snapshots of this WritableSnapshotsResponse.  # noqa: E501


        :return: The snapshots of this WritableSnapshotsResponse.  # noqa: E501
        :rtype: list[WritableSnapshotModel]
        """
        return self._snapshots

    @snapshots.setter
    def snapshots(self, snapshots):
        """Sets the snapshots of this WritableSnapshotsResponse.


        :param snapshots: The snapshots of this WritableSnapshotsResponse.  # noqa: E501
        :type: list[WritableSnapshotModel]
        """

        self._snapshots = snapshots

    @property
    def success(self):
        """Gets the success of this WritableSnapshotsResponse.  # noqa: E501

        API Status  # noqa: E501

        :return: The success of this WritableSnapshotsResponse.  # noqa: E501
        :rtype: str
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this WritableSnapshotsResponse.

        API Status  # noqa: E501

        :param success: The success of this WritableSnapshotsResponse.  # noqa: E501
        :type: str
        """

        self._success = success

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WritableSnapshotsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WritableSnapshotsResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, WritableSnapshotsResponse):
            return True

        return self.to_dict() != other.to_dict()
